mvcmusicsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('mvcmusicsite_app.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

mvcmusicsite_app/urls.py
from django.conf.urls import url

from . import views
from mvcmusicsite_app.models import Album
from django_filters.views import FilterView

app_name = 'music_site'
urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^home/$', views.Home.as_view(), name='home'),
    url(r'^genres/$', views.GenreList.as_view(), name='genres'),
    url(r'^albums/$', views.album_list, name='albums'),
    url(r'^artists/$', views.ArtistList.as_view(), name='artists'),
    url(r'^album/add_to_basket/$', views.add_to_basket, name='add_to_basket'), # dont use ajax in your url name - needs to make sense on what object you acting on
    url(r'^mybasket/$', views.BasketItemsListView.as_view(), name='my_basket'),
    url(r'^album/remove_from_basket/$', views.remove_from_basket, name='remove_from_basket'),
    url(r'^signup/$', views.CreateAccount.as_view(), name='signup'),
    url(r'^checkout/$', views.Checkout.as_view(), name='checkout'),
]

mvcmusicsite_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser, User



# Create your models here. from mvcmusicsite_app.models import *

class Basket(models.Model):

    creation_date = models.DateTimeField(auto_now_add=True)
    checked_out = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.user)

    @property
    def items(self):
        if self.basketitem_set.exists():
            return self.basketitem_set.count()
        return 0

class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Artist(models.Model):

    name = models.CharField(max_length=100)
    genres = models.ManyToManyField(Genre, blank=True)

    def __str__(self):
        return self.name

class Album(models.Model):

    title = models.CharField(max_length=100)
    year = models.DateField(null=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    artists = models.ManyToManyField(Artist, blank=True)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.SET_NULL)


    def __str__(self):
        return self.title

class BasketItem(models.Model):

    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    item = models.ForeignKey(Album, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.item.title

mvcmusicsite_app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")
        help_texts = {
        'username': None
        }


    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

mvcmusicsite_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic import TemplateView, CreateView
from django.views.generic.list import ListView
from mvcmusicsite_app.models import Album, Artist, Genre, BasketItem, Basket
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django_filters.views import FilterView
from .forms import UserCreateForm
from django.contrib.auth import authenticate, login
from .utils import get_basket




import django_filters
import json


# Create your views here.

class CreateAccount(CreateView):

    redirect_field_name = 'music_site:home'

    template_name = 'create_account_form.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('music_site:home')

    def form_valid(self, form):

        context = super(CreateAccount, self).form_valid(form)

        print (self.object.first_name)

        login(self.request, self.object)
        basket = Basket.objects.get(id=self.request.session['basket'])
        basket.user = self.object
        basket.save()

        return context





class BasketItemsListView(ListView):
    """
    View listing items in basket of current user.
    """
    def get_context_data(self, **kwargs):
    	context = super(BasketItemsListView, self).get_context_data(**kwargs)
    	context['page'] = 'my_basket'
        context['basket'] = get_basket(self.request)
    	return context

    template_name ='basket_item_view_current_user.html'
    model = BasketItem
    paginate_by = 15

    def get_queryset(self):

        basket = get_basket(self.request)
        return basket.basketitem_set.order_by('item')


class Home(TemplateView):

    template_name = 'home.html'

    def get_context_data(self, **kwargs):
    	context = super(Home, self).get_context_data(**kwargs)
    	context['page'] = 'home'
        context['basket'] = get_basket(self.request)
    	return context

class Checkout(TemplateView):

    template_name = 'checkout.html'


class GenreList(ListView):

    template_name = 'genres.html'
    model = Genre
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(GenreList, self).get_context_data(**kwargs)
        context['page'] = 'genres'
        context['basket'] = get_basket(self.request)
        return context

class ArtistList(ListView):

    template_name = 'artists.html'
    model = Artist
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(ArtistList, self).get_context_data(**kwargs)
        context['page'] = 'artists'
        context['basket'] = get_basket(self.request)
        return context


def add_to_basket(request):

    data = {}
    data['success'] = False

    item_id = request.POST.get('album_id', 0)

    basket = get_basket(request)

    try:

        basketitem = Album.objects.get(id=item_id)

    except Album.DoesNotExist:
        return JsonResponse(data)

    BasketItem.objects.create(basket=basket, item=basketitem)
    data['success'] = True

    return JsonResponse(data)


    #
    # if request.user.is_authenticated:
    #     basket, _ = Basket.objects.get_or_create(user=request.user)
    #     try:
    #
    #         basketitem = Album.objects.get(id=item_id)
    #
    #     except Album.DoesNotExist:
    #         return JsonResponse(data)
    #
    #     BasketItem.objects.create(basket=basket, item=basketitem)
    #     data['success'] = True
    #
    #     return JsonResponse(data)
    #
    # elif not request.user.is_authenticated:
    #
    #     data = {}
    #     data['success'] = False
    #     item_id = request.POST.get('album_id', 0)
    #
    #
    #     if 'Basket' in request.session:
    #
    #         print (request.session['Basket'])
    #         basket = Basket.objects.get(id=request.session['Basket'])
    #
    #         try:
    #             basketitem = Album.objects.get(id=item_id)
    #
    #         except Album.DoesNotExist:
    #             return JsonResponse(data)
    #
    #         BasketItem.objects.create(basket=basket, item=basketitem)
    #         data['success'] = True
    #
    #         return JsonResponse(data)
    #
    #
    #     else:
    #
    #         basket = Basket.objects.create()
    #         request.session['Basket'] = basket.id
    #
    #         try:
    #             basketitem = Album.objects.get(id=item_id)
    #
    #         except Album.DoesNotExist:
    #             return JsonResponse(data)
    #
    #         BasketItem.objects.create(basket=basket, item=basketitem)
    #         data['success'] = True
    #
    #         return JsonResponse(data)



@login_required
def remove_from_basket(request):

    data = {}
    basketitem_id = request.POST.get('basket_item_id', 0)

    data['success'] = False

    try:
        basket_item = BasketItem.objects.filter(id=basketitem_id)

    except BasketItem.DoesNotExist:
        return JsonResponse(data)

    basket_item.delete()
    data['success'] = True

    return JsonResponse(data)




# class AlbumList(ListView):
#
#     template_name = 'albums.html'
#     model = Album
#     paginate_by = 15
#
#     def get_context_data(self, **kwargs):
#         context = super(AlbumList, self).get_context_data(**kwargs)
#         context['page'] = 'albums'
#         return context


class LogoutView(TemplateView):

    template_name = 'registration/logout.html'



class AlbumFilter(django_filters.FilterSet):
    artists__name = django_filters.CharFilter(lookup_expr='icontains')
    genre__name = django_filters.CharFilter(lookup_expr='icontains')
    title = django_filters.CharFilter(lookup_expr='icontains')

    class Meta:
        model = Album
        exclude = ['year', 'price', 'genre', 'artists', 'title']



def album_list(request):

    def get_context_data(self, **kwargs):
        context = super(AlbumFilter, self).get_context_data(**kwargs)
        context['basket'] = get_basket(self.request)
        return context

    f = AlbumFilter(request.GET, queryset=Album.objects.all().order_by('title'))
    return render(request, 'album_filter.html', {'filter': f})

mvcmusicsite_app/templates/album_filter.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/albums.js' %}"></script>
    <script type="text/javascript">
      var basket_url = "{% url 'music_site:add_to_basket' %}";
    </script>
{% endblock %}


{% block titlebar %} Albums {% endblock %}

{% block content %}

<div class="section">

    <table class="responsive-table striped highlight">
      <thead>
        <tr class="blue-text text-darken-1">
          <th>Album</th>
          <th>Artist</th>
          <th>Price</th>
          <th class="right-align"><i class="material-icons right">add_shopping_cart</i>Add to basket</th>
        </tr>
      </thead>
     <tbody>

    <div class="row">
        <form action="" method="get">
            {% for field in filter.form %}
            <div class="col s3">
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <button class="btn-floating waves-effect waves-light hoverable" type="search" name="action">
                <i class="material-icons right">filter_list</i>
            </button>
            <button id="clear-filter" class="btn-floating waves-effect waves-light hoverable" type="reset" value="Reset">
                <i class="material-icons right">clear</i>
            </button>
        </form>
    </div>
    {% for obj in filter.qs %}
        <tr>
          <div>
            <td>
              {{ obj.title }}
            </td>
          </div>
          <div>
            <td>
              {% for a in obj.artists.all %} {{ a.name }} {% endfor %}
            </td>
          </div>
          <div>
            <td>
              £{{ obj.price }}
            </td>
          </div>
          <div>
            <td><a data-album="{{ obj.id }}" class="js-add-album btn-floating waves-effect waves-light right hoverable"><i class="material-icons">add</i></a></td>
          </div>
        </tr>
    {% endfor %}
      </tbody>
    </table>
    {% include "pagination.html" %}

</div>

{% endblock %}

mvcmusicsite_app/templates/artists.html
{% extends "base.html" %}


{% block titlebar %} Artists {% endblock %}

{% block content %}

<div class="section">


  <div class="row">
    <table class="striped highlight responsive-table">
      <thead>
        <tr class="blue-text text-darken-1">
          <th>Artist</th>
          <th>Genre</th>
        </tr>
      </thead>
      <tbody>
        {% for artist in object_list %}
        <tr>
          <div class="col s6">
            <td>
              {{ artist.name }}
            </td>
          </div>
          <div class="col s6">
            <td>
              {% for g in artist.genres.all %} {{ g.name }} {% endfor %}
            </td>
          </div>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include "pagination.html" %}

  </div>

</div>



{% endblock %}

mvcmusicsite_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="/static/fontawesome/web-fonts-with-css/css/fontawesome-all.css" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}" media="screen,projection" />
  <link type="text/css" rel="stylesheet" href="{% static 'css/music_site.css' %}" />
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'js/cookie.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/music-site.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
  {% block scripts %}{% endblock %}

  <title>{% block titlebar %}{% endblock %}</title>
</head>

<body>

  {% block index_features %}


  <nav>
    <div class="nav-wrapper z-depth-3" style="background-color: #a7e2e3">
      <a href="{% url 'music_site:home' %}" class="brand-logo center"><i class="material-icons">music_note</i></a>
      <ul id="nav-mobile" class="left">
        <li><a class="white-text" href="{% url 'music_site:home' %}">Home</a></li>
        <li><a class="white-text" href="{% url 'music_site:genres' %}">Genres</a></li>
        <li><a class="white-text" href="{% url 'music_site:albums' %}">Albums</a></li>
        <li><a class="white-text" href="{% url 'music_site:artists' %}">Artists</a></li>
      </ul>
      <ul class="right">

        <li><a id="basket-icon" class="btn" data-hover="true" href="{% url 'music_site:my_basket' %}">
            <div style='position:relative'>
                <i class="fa fa-shopping-cart" style="top:4px"></i>
                <span style="position:absolute; top:6px; color:black">{{basket.items}}</span>
            </div>
            </a>
        </li>
        <li><a class="white-text dropdown-button btn" data-hover="true" href="#" data-activates="dropdown-2"><i class="material-icons">account_circle</i></a>
          <ul id="dropdown-2" class="dropdown-content">
            {% if user.is_authenticated %}
              <li><a href="#">User: {{ user.get_username }}</a></li>
              <li><a href="{% url 'logout' %}?next=/home/">Logout</a></li>
            {% else %}
              <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
              <li><a href="{% url 'music_site:signup' %}">Create account</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </nav>



  {% endblock %}

  <div class="container">
  {% block content %}  {% endblock %}
  </div>

  <footer class="page-footer" style="background-color: #a7e2e3">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5>MVC Music</h5>
          <p class="white-text">For the latest and greatest in music.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Shop</h5>
          <ul>
            <li><a class="white-text" href="{% url 'music_site:home' %}">Home</a></li>
            <li><a class="white-text" href="{% url 'music_site:genres' %}">Genres</a></li>
            <li><a class="white-text" href="{% url 'music_site:albums' %}">Albums</a></li>
            <li><a class="white-text" href="{% url 'music_site:artists' %}">Artists</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright" style="background-color: #a7e2e3">
      <div class="container white-text">
        © {% now "Y" %} Sophie Wendell
        <a class="white-text right-align" href="#!">Portfolio</a>
      </div>
    </div>
  </footer>

</body>

</html>

mvcmusicsite_app/templates/basket_item_view_current_user.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/delete_item.js' %}"></script>
    <script type="text/javascript">
      var remove_basket_url = "{% url 'music_site:remove_from_basket' %}";
    </script>
{% endblock %}

{% block titlebar %} Basket {% endblock %}



{% block content %}
    <h3 style="color: #26a69a">Items in Basket</h3>

    {% if object_list %}
    <ul>

      {% for basketitem in object_list %}
      <li id="item_{{ basketitem.id }}" style="padding:10px">
        {{ basketitem.item.title }} - £{{ basketitem.item.price }}
        <a data-basket_item="{{ basketitem.id }}" class="js-delete-album btn-floating btn waves-effect waves-light red" type='submit' style="margin-left:15px"><i class="material-icons">clear</i></a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no items in your basket.</p>
    {% endif %}

    {% if user.is_authenticated %}
    <a class="btn" href="{% url 'music_site:checkout' %}" style:"margin-bottom:10px">Checkout</a>
    {% else %}
    <a class="btn" href="{% url 'music_site:signup' %}" style:"margin-bottom:10px">Register</a>
    {% endif %}
{% endblock %}

mvcmusicsite_app/templates/checkout.html
{% extends "base.html" %}
{% load static %}

{% block titlebar %}
    Checkout
{% endblock %}

{% block content %}

    <h1>Items ordered!</h1>

{% endblock %}

mvcmusicsite_app/templates/create_account_form.html
{% extends "base.html" %}

{% block titlebar %}
  Create Account
{% endblock %}

{% block content %}

<div class="section">
    <h5>Create Account</h5>

    <form method="post" class="validate">{% csrf_token %}
        {{ form }}


                <div class="right-align">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Create Account
                        <i class="material-icons right">send</i>
                    </button>

                </div>



    </form>
</div>








{% endblock %}

mvcmusicsite_app/templates/footer.html
<footer class="page-footer z-depth-3" style="background-color: #a7e2e3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5>MVC Music</h5>
        <p class="white-text">For the latest and greatest in music.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Shop</h5>
        <ul>
          <li><a class="white-text" href="{% url 'music_site:home' %}">Home</a></li>
          <li><a class="white-text" href="{% url 'music_site:genres' %}">Genres</a></li>
          <li><a class="white-text" href="{% url 'music_site:albums' %}">Albums</a></li>
          <li><a class="white-text" href="{% url 'music_site:artists' %}">Artists</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright" style="background-color: #a7e2e3">
    <div class="container white-text">
      © {% now "Y" %} Sophie Wendell
      <a class="white-text right-align" href="#!">Portfolio</a>
    </div>
  </div>
</footer>

mvcmusicsite_app/templates/genres.html
{% extends "base.html" %}

{% block titlebar %}
  Genres
{% endblock %}

{% block content %}

<div class="section">


  <div class="row">
    <table class="highlight centered responsive-table">
      <thead>
        <tr class="blue-text text-darken-1">
          <th>Genre</th>
        </tr>
      </thead>
      <tbody>
        {% for genre in object_list %}
        <tr>
          <td>
            {{ genre.name }}
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
    {% include "pagination.html" %}
  </div>

</div>

{% endblock %}

mvcmusicsite_app/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block titlebar %}
  Home
{% endblock %}

{% block content %}
<div class="section">
  <div class="section"><h5 class="center-align thick" style="color: #ffc857">Finding fresh music has never been easier.</h5></div>
  <div class="divider"></div>


  <div class="section z-depth-2" style="color: #ffc857">
    <h3 class="condensed light center-align">Featured Albums</h3>

      <div class="carousel">
        <a class="carousel-item center-align" href="#one!" style="color: #808782"><img src="{% static 'img/everyday_is_christmas.jpg' %}"/>Every Day Is Christmas</a>
        <a class="carousel-item center-align" href="#two!" style="color: #808782"><img src="{% static 'img/the_suburbs.jpg' %}"/>The Suburbs</a>
        <a class="carousel-item center-align" href="#three!" style="color: #808782"><img src="{% static 'img/broken_machine.jpg' %}"/>Broken Machine</a>
        <a class="carousel-item center-align" href="#four!" style="color: #808782"><img src="{% static 'img/la_la_land.jpg' %}"/>La La Land Soundtrack</a>
        <a class="carousel-item center-align" href="#four!" style="color: #808782"><img src="{% static 'img/because_the_internet.jpg' %}"/>Because The Internet</a>
      </div>
      <div class="divider">

      </div>
      <div class="section" style="color: #ffc857">
        <h3 class="condensed light center-align">Featured Artists</h3>

          <div class="carousel">
            <a class="carousel-item center-align" href="http://twodoorcinemaclub.com/" style="color: #808782" target="_blank"><img class="circle" src="{% static 'img/two_door_cinema_club.jpg' %}"/>Two Door Cinema Club</a>
            <a class="carousel-item center-align" href="https://awakenmylove.com/" style="color: #808782" target="_blank"><img class="circle" src="{% static 'img/childish_gambino.jpg' %}"/>Childish Gambino</a>
            <a class="carousel-item center-align" href="https://falloutboy.com/" style="color: #808782" target="_blank"><img class="circle" src="{% static 'img/fall_out_boy.jpg' %}"/>Fall Out Boy</a>
            <a class="carousel-item center-align" href="http://www.siamusic.net/" style="color: #808782" target="_blank"><img class="circle" src="{% static 'img/sia.jpg' %}"/>Sia</a>
            <a class="carousel-item center-align" href="http://www.nbthieves.com/" style="color: #808782" target="_blank"><img class="circle" src="{% static 'img/nothing_but_thieves.jpg' %}"/>Nothing But Thieves</a>
          </div>

        </div>
      </div>
  </div>
{% endblock %}

mvcmusicsite_app/templates/index.html
{% extends "base.html" %}

mvcmusicsite_app/templates/pagination.html
{% if is_paginated %}

<ul class="pagination right-align">
  <span class="page-links">
           {% if page_obj.has_previous %}
               <li class="waves-effect"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
           {% else %}
              <li class="disabled"><i class="material-icons">chevron_left</i></li>
           {% endif %}
           <span class="page-list">
             {% for p in page_obj.paginator.page_range %}
               <li class="waves-effect {% if p == page_obj.number %} active {% endif %}"><a href="?page={{ p }}">{{ p }}</a></li>
             {% endfor %}
           </span>
           {% if page_obj.has_next %}
               <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
           {% endif %}
   </span>
</ul>
{% endif %}